name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 添加權限設定
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup Streamlit config
      run: |
        mkdir -p ~/.streamlit
        echo "[server]" > ~/.streamlit/config.toml
        echo "headless = true" >> ~/.streamlit/config.toml
        echo "enableCORS = false" >> ~/.streamlit/config.toml
        echo "port = ${{ env.PORT || 8501 }}" >> ~/.streamlit/config.toml
        
    - name: Create Streamlit app files
      run: |
        mkdir -p build
        cp -r src/* build/
        cp requirements.txt build/
        cp README.md build/
        # 建立 streamlit 啟動檔案
        echo "import streamlit as st" > build/streamlit_app.py
        echo "import sys" >> build/streamlit_app.py
        echo "import os" >> build/streamlit_app.py
        echo "sys.path.append(os.path.dirname(__file__))" >> build/streamlit_app.py
        echo "from app import main" >> build/streamlit_app.py
        echo "if __name__ == '__main__':" >> build/streamlit_app.py
        echo "    main()" >> build/streamlit_app.py

    - name: Setup Pages
      uses: actions/configure-pages@v4
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true 