name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Streamlit config
      run: |
        mkdir -p ~/.streamlit
        echo '[server]' > ~/.streamlit/config.toml
        echo 'headless = true' >> ~/.streamlit/config.toml
        echo 'enableCORS = false' >> ~/.streamlit/config.toml
        echo 'port = ${{ env.PORT || 8501 }}' >> ~/.streamlit/config.toml
        
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: src
        branch: gh-pages 